# Generated by Django 4.1.7 on 2023-02-26 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0002_alter_gst_cgst_alter_gst_igst_alter_gst_sgst_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='sales_app.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='invoice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_invoice', to='sales_app.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='product_invoice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_list', to='stocks_app.product'),
        ),
    ]
