# Generated by Django 4.1.7 on 2023-02-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0002_alter_gst_cgst_alter_gst_igst_alter_gst_sgst_and_more'),
        ('purchase_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendors',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors_order', to='purchase_app.vendors'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_order', to='purchase_app.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_list', to='stocks_app.product'),
        ),
    ]
