# Generated by Django 4.1.7 on 2023-02-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0002_alter_order_vendors_alter_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
